# This is a basic workflow to help you get started with Actions

name: fork-issues

# Controls when the workflow will run
on:
  # Triggers the workflow on fork
  [fork]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.1
      - name: Action test
        id: my_action
        uses: Minegarde/fork-issues@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Log the forkee
        run: |
          echo  Owner: ${{ steps.my_action.outputs.created.owner }}
          echo  Repo: ${{ steps.my_action.outputs.created.repo }}